#pragma once

#include "NativeGameplayTags.h"


// ----- Ability Fragment -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_Sellable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_Equipable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_DisplayUI);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_SetStat);

// ----- Static Fragment -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_Consumable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_Module);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_MaterialItem);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_QuestItem);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_CostumeItem);
