#pragma once

#include "NativeGameplayTags.h"

// ----- Ability Fragment -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_Sellable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_Equipable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_SetIcon);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_SetStat);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_ConsumeAbility);

// ----- Static Fragment -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_CostumeItem);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_MaterialItem);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_QuestItem);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_SwordModule);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_GunModule);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_WeaponGunStats);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Fragment_WeaponSwordStats);
