#pragma once

#include "NativeGameplayTags.h"

namespace KRGameplayTags
{
	/* Input Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Gun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_Gun);
	/* State Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Attaking);

	/* Player Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Gun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Can_Step);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Can_Jump);

	/* Event Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Equip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Unequip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Equip_Gun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Unequip_Gun);

	/* Ability Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Equip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Unequip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Equip_Gun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Unequip_Gun);
}
