#pragma once

#include "NativeGameplayTags.h"

namespace KRGameplayTags
{
	/* Input Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);

	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_GASprint);

	/* State Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Attaking);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Sprinting);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Steping);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Jumping);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Laddering);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Interacting);

	/*Action Tags*/
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Action_Step);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Action_Jump);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Action_Ladder);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Can_Step);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Can_Jump);
	
	/*Cooldown Tags*/
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability);
}
