#pragma once

#include "NativeGameplayTags.h"

namespace KRGameplayTags
{
	/* Input Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);

	// ----- ItemType -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType);

	// ----- ItemType.Equip -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Sword);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Gun);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_GunModule);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_SwordModule);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Armor);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Head);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Costume);

	// ----- ItemType.Consume -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_Potion);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_InsuranceCoin);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_InsuranceWallet);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_Key);

	// ----- ItemType.Tool -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Tool);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Tool_Light);

	// ----- ItemType.Material -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material_Scrap);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material_Tech);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material_Doc);

	// ----- ItemType.Quest -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Quest);

	// ----- Weapon -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Gun_CritMultiplier);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Sword_CritMultiplier);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Both_AttackSpeed);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Gun_Accuracy);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Gun_Recoil);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Gun_ExtendMag);

	// ----- Ability -----

	/* State Tags */
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Acting_Attaking);

	// ----- Item Property -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Property);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Property_Stackable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Property_Buyable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Property_Sellable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Item_Property_Unsellable);

	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Can_Step);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Can_Jump);
	
	// ----- Pool -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Pool_AlwaysOn);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Pool_Rotation_R1);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Pool_Rotation_R2);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Pool_Rotation_R3);

	// ----- Ability.Item -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Item_Stackable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Item_Buyable);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Item_Sellable);

	// ----- Ability.Consume -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Heal);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Stamina);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_CoreCharge);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_ATKBuff);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Stealth);

	// ----- Ability.Tool -----
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Tool_Light);

	// ===== Rarity =====
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Rarity_Common);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Rarity_Uncommon);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Rarity_Rare);
	KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Rarity_Epic);

	// ----- Item Consume Effect ----

	// ----- Item Tool Effect ----

	// ----- Equipment Slot -----

}