#pragma once

#include "NativeGameplayTags.h"

// ----- Ability.Item -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Item_Stackable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Item_Buyable);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Item_Sellable);

// ----- Ability.Consume -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Heal);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Stamina);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_CoreCharge);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_ATKBuff);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Stealth);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Consume_Light);

// ----- Ability.Equip / Unequip -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Equip_Sword);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Equip_Gun);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Unequip_Sword);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Unequip_Gun);
