#pragma once

#include "NativeGameplayTags.h"

// ----- ItemType -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType);

// ----- ItemType.Equip -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Sword);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Gun);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_GunModule);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_SwordModule);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Armor);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Head);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Equip_Costume);

// ----- ItemType.Consume -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_Potion);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_InsuranceCoin);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_InsuranceWallet);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Consume_Key);

// ----- ItemType.Tool -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Tool);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Tool_Light);

// ----- ItemType.Material -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material_Scrap);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material_Tech);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Material_Doc);

// ----- ItemType.Quest -----
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ItemType_Quest);
