#include "KRAbilityTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ELEMENTAL_FIRE, "Ability.Elemental.Fire");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ELEMENTAL_ICE, "Ability.Elemental.Ice");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ELEMENTAL_ELECTRONIC, "Ability.Elemental.Electronic");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ELEMENTAL_DARK, "Ability.Elemental.Dark");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_APPLYCC_STUN, "Ability.ApplyCC.Stun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_APPLYCC_SLOW, "Ability.ApplyCC.Slow");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_APPLYCC_GROGGY, "Ability.ApplyCC.Groggy");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_STACKABLE, "Ability.Item.Stackable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_BUYABLE, "Ability.Item.Buyable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_SELLABLE, "Ability.Item.Sellable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_DISPLAYUI, "Ability.Item.DisplayUI");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_SETSTAT, "Ability.Item.SetStat");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_CONSUME, "Ability.Item.Consume");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ITEM_QUICKSLOT, "Ability.Item.QuickSlot");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_CONSUME_HEAL, "Ability.Consume.Heal");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_CONSUME_STAMINA, "Ability.Consume.Stamina");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_CONSUME_CORECHARGE, "Ability.Consume.CoreCharge");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_CONSUME_ATKBUFF, "Ability.Consume.AtkBuff");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_CONSUME_STEALTH, "Ability.Consume.Stealth");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_CONSUME_LIGHT, "Ability.Consume.Light");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_WEAPON_SWITCH, "Ability.Weapon.Switch");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_WEAPON_EQUIP, "Ability.Weapon.Equip");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_WEAPON_UNEQUIP, "Ability.Weapon.Unequip");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_SCAN, "Ability.Scan");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_STEP, "Ability.Step");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_JUMP, "Ability.Jump");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_SPRINT, "Ability.Sprint");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_INTERACT, "Ability.Interact");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_GRAPPLE, "Ability.Grapple");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_LADDER, "Ability.Ladder");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_BOXOPEN, "Ability.BoxOpen");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_NPCINTERACT, "Ability.NPCInteract");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_LOCKON, "Ability.LockOn");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_GUARD, "Ability.Guard");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_DEATH, "Ability.Death");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_HITREACTION, "Ability.HitReaction");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ATTACK_LIGHTATTACK, "Ability.Attack.LightAttack");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ATTACK_CHARGEATTACK, "Ability.Attack.ChargeAttack");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ATTACK_COREDRIVESURGE, "Ability.Attack.CoreDriveSurge");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_ATTACK_COREDRIVEBURST, "Ability.Attack.CoreDriveBurst");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_NPCINTERACT_SHOP, "Ability.NPCInteract.Shop");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_NPCINTERACT_WEAPONUPGRADE, "Ability.NPCInteract.WeaponUpgrade");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ABILITY_NPCINTERACT_CLARA, "Ability.NPCInteract.Clara");
