#include "KRBossTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_BOSS_PHASE, "Boss.Phase");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_BOSS_AISTATE_ENRAGE, "Boss.AIState.Enrage");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_BOSS_IMMUNE_GRAPPLE, "Boss.Immune.Grapple");
