
#pragma once

#include "NativeGameplayTags.h"

// ============================================================
// COMBAT TAGS - For CombatActionData
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_ATTACK_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_ATTACK_HEAVY);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_ATTACK_CHARGE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_ATTACK_AERIAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_ATTACK_FINISHER);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_DEFENSE_GUARD);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_DEFENSE_PARRY);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_GUN_FIRE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_GUN_RELOAD);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_DODGE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_COMBAT_ROLL);

// ============================================================
// HIT REACTION TAGS
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_HITREACTION_NORMAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_HITREACTION_CRITICAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_HITREACTION_STUN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_HITREACTION_KNOCKBACK);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_HITREACTION_KNOCKDOWN);

// ============================================================
// WORLD EVENT TAGS
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_ENVIRONMENT_DOOR_OPEN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_ENVIRONMENT_LADDER_ENTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_CHEST_OPEN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_PICKUP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_SCAN_SENSE_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_SCAN_SENSE_ENEMY);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_LADDER_CLIMB);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_BOX_OPEN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_WORLDEVENT_INTERACTION_SAVE_FIRE);