
#pragma once

#include "NativeGameplayTags.h"

// ============================================================
// EFFECT TAGS - Movement
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_STONE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_GRASS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_SAND);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_METAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_WALK_WOOD);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_STONE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_GRASS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_SAND);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_METAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_FOOTSTEP_RUN_WOOD);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_NORMAL_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_NORMAL_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_NORMAL_WOOD);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_NORMAL_CONCRETE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_HEAVY_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_HEAVY_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_HEAVY_WOOD);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOVEMENT_LANDING_HEAVY_CONCRETE);

// ============================================================
// EFFECT TAGS - Mobility
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOBILITY_DODGE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_MOBILITY_ROLL);

// ============================================================
// EFFECT TAGS - Stealth
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_STEALTH_ENTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_STEALTH_EXIT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_STEALTH_KILL);

// ============================================================
// EFFECT TAGS - Combat Sword
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_ATTACK_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_ATTACK_COMBO1);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_ATTACK_COMBO2);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_ATTACK_COMBO3);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_ATTACK_HEAVY);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_CHARGE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_SWORD_CHARGE_RELEASE);

// ============================================================
// EFFECT TAGS - Combat Gun
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_GUN_FIRE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_GUN_SHELL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_COMBAT_GUN_TRACER);

// ============================================================
// EFFECT TAGS - Defense
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DEFENSE_GUARD_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DEFENSE_GUARD_IMPACT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DEFENSE_GUARD_DEFLECT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DEFENSE_PARRY_SUCCESS);

// ============================================================
// EFFECT TAGS - Damage & Impact
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DAMAGE_HIT_PLAYER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DAMAGE_HIT_ENEMY_HUMAN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DAMAGE_HIT_ENEMY_MONSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_DAMAGE_HIT_ENEMY_SEMIBOSS);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_SWORD_ENEMY_HUMAN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_SWORD_ENEMY_MONSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_SWORD_ENEMY_SEMIBOSS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_SWORD_ENVIRONMENT);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_GUN_ENEMY_HUMAN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_GUN_ENEMY_MONSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_GUN_ENEMY_SEMIBOSS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_GUN_ENVIRONMENT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_IMPACT_GUN_RICOCHET);

// ============================================================
// EFFECT TAGS - UI & Resources
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_UI_STAMINA_DEPLETED);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_UI_COREDRIVE_CHARGE1);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_UI_COREDRIVE_CHARGEFULL);

// ============================================================
// EFFECT TAGS - Interaction
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_INTERACTION_PICKUP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_INTERACTION_CHEST_COMPLETE);

// ============================================================
// EFFECT TAGS - Boss
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_BOSS_INTRO);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_BOSS_AURA);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_BOSS_PHASETRANSITION);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_BOSS_ATTACKTELEGRAPH);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_BOSS_AREAATTACK);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_BOSS_DEATH);

// ============================================================
// EFFECT TAGS - Category (for filtering/pooling)
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_CATEGORY_COMBAT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_CATEGORY_WEAPON);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_CATEGORY_IMPACT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_CATEGORY_ENVIRONMENT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_EFFECT_CATEGORY_UI);
