#include "KREnemyTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ACTION_SLASH, "Enemy.Action.Slash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ACTION_SHOOT, "Enemy.Action.Shoot");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_PATROL, "Enemy.AIState.Patrol");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_ALERT, "Enemy.AIState.Alert");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_COMBAT, "Enemy.AIState.Combat");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_COVER, "Enemy.AIState.Cover");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_CHASE, "Enemy.AIState.Chase");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_DEAD, "Enemy.AIState.Dead");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_HITREACTION, "Enemy.AIState.HitReaction");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_RAGE, "Enemy.AIState.Rage");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_HUMAN_MELEE, "Enemy.Type.Human.Melee");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_HUMAN_RANGED, "Enemy.Type.Human.Ranged");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_FERROLOADER, "Enemy.Type.FerroLoader");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_ARBID, "Enemy.Type.Arbid");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_SPINDERBREED, "Enemy.Type.SpinderBreed");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_NERRAS, "Enemy.Type.Nerras");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK1, "Enemy.FerroLoader.Attack1");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK1_START, "Enemy.FerroLoader.Attack1.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK1_END, "Enemy.FerroLoader.Attack1.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK2, "Enemy.FerroLoader.Attack2");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK2_START, "Enemy.FerroLoader.Attack2.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK2_END, "Enemy.FerroLoader.Attack2.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK3, "Enemy.FerroLoader.Attack3");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK3_START, "Enemy.FerroLoader.Attack3.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK3_END, "Enemy.FerroLoader.Attack3.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK4, "Enemy.FerroLoader.Attack4");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK4_START, "Enemy.FerroLoader.Attack4.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_ATTACK4_END, "Enemy.FerroLoader.Attack4.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_RAGEATTACK1, "Enemy.FerroLoader.RageAttack1");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_RAGEATTACK1_START, "Enemy.FerroLoader.RageAttack1.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_FERROLOADER_RAGEATTACK1_END, "Enemy.FerroLoader.RageAttack1.End");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK1, "Enemy.Arbid.Attack1");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK1_START, "Enemy.Arbid.Attack1.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK1_END, "Enemy.Arbid.Attack1.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK2, "Enemy.Arbid.Attack2");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK2_START, "Enemy.Arbid.Attack2.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK2_END, "Enemy.Arbid.Attack2.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK3, "Enemy.Arbid.Attack3");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK3_START, "Enemy.Arbid.Attack3.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ARBID_ATTACK3_END, "Enemy.Arbid.Attack3.End");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK1, "Enemy.SpinderBreed.Attack1");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK1_START, "Enemy.SpinderBreed.Attack1.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK1_END, "Enemy.SpinderBreed.Attack1.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK2, "Enemy.SpinderBreed.Attack2");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK2_START, "Enemy.SpinderBreed.Attack2.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK2_END, "Enemy.SpinderBreed.Attack2.End");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK3, "Enemy.SpinderBreed.Attack3");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK3_START, "Enemy.SpinderBreed.Attack3.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_SPINDERBREED_ATTACK3_END, "Enemy.SpinderBreed.Attack3.End");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_IMMUNE_GRAPPLE, "Enemy.Immune.Grapple");

