#include "KREnemyTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ACTION_SLASH, "Enemy.Action.Slash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_ACTION_SHOOT, "Enemy.Action.Shoot");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_PATROL, "Enemy.AIState.Patrol");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_ALERT, "Enemy.AIState.Alert");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_COMBAT, "Enemy.AIState.Combat");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_COVER, "Enemy.AIState.Cover");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_CHASE, "Enemy.AIState.Chase");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_DEAD, "Enemy.AIState.Dead");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_AISTATE_HITREACTION, "Enemy.AIState.HitReaction");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_HUMAN_MELEE, "Enemy.Type.Human.Melee");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_HUMAN_RANGED, "Enemy.Type.Human.Ranged");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_FERROLOADER, "Enemy.Type.FerroLoader");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_ARBID, "Enemy.Type.Arbid");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_SPINDERBREED, "Enemy.Type.SpinderBreed");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_TYPE_NERRAS, "Enemy.Type.Nerras");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ENEMY_IMMUNE_GRAPPLE, "Enemy.Immune.Grapple");

