#include "KREventTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_HIT, "Event.Combat.Hit");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_HITREACTION, "Event.Combat.HitReaction");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_PARRYSUCCESS, "Event.Combat.ParrySuccess");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_GUARDBROKEN, "Event.Combat.GuardBroken");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_DEATH, "Event.Combat.Death");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_CATALYST_FULL, "Event.Catalyst.Full");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_CATALYST_SURGE, "Event.Catalyst.Surge");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_CATALYST_BURST, "Event.Catalyst.Burst");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_STAMINA_EMPTY, "Event.Stamina.Empty");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COREDRIVE_CHARGE_ONHIT, "Event.CoreDrive.Charge.OnHit");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COREDRIVE_CHARGE_ONPARRY, "Event.CoreDrive.Charge.OnParry");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COREDRIVE_CHARGE_ONKILL, "Event.CoreDrive.Charge.OnKill");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COREDRIVE_FULL, "Event.CoreDrive.Full");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COREDRIVE_DASH_HITCHECK, "Event.CoreDrive.Dash.HitCheck");

// 근접 공격 히트 체크 이벤트
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_MELEE_HITCHECK_BEGIN, "Event.Melee.HitCheck.Begin");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_MELEE_HITCHECK_TICK, "Event.Melee.HitCheck.Tick");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_MELEE_HITCHECK_END, "Event.Melee.HitCheck.End");

// 적 슬래시 히트 체크 이벤트
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_ENEMY_SLASH_HITCHECK, "Event.Enemy.Slash.HitCheck");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_EQUIP_SWORD, "Event.Equip.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_EQUIP_GUN, "Event.Equip.Gun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_UNEQUIP_SWORD, "Event.Unequip.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_UNEQUIP_GUN, "Event.Unequip.Gun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_LADDER_TOP, "Event.Ladder.Top");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_LADDER_BOTTOM, "Event.Ladder.Bottom");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ABILITY, "Cooldown.Ability");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ABILITY_JUMP, "Cooldown.Ability.Jump");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM, "Cooldown.Item");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_COMMON, "Cooldown.Item.Common");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_FIRSTAID, "Cooldown.Item.FirstAid");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_STAMINA, "Cooldown.Item.Stamina");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_VIOLICALL, "Cooldown.Item.ViolicAll");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_COREBATTERY, "Cooldown.Item.CoreBattery");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_FORGOTTENCITY_MISSIONAREA, "Event.ForgottenCity.MissionArea");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_FORGOTTENCITY_ACCESSPOINT, "Event.ForgottenCity.AccessPoint");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_FORGOTTENCITY_BOSSARENA, "Event.ForgottenCity.BossArena");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_FORGOTTENCITY_FINALBOSSARENA, "Event.ForgottenCity.FinalBossArena");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_DIALOGUE_START, "Event.Dialogue.Start");