#include "KREventTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_HIT, "Event.Combat.Hit");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_PARRYSUCCESS, "Event.Combat.ParrySuccess");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_COMBAT_GUARDBROKEN, "Event.Combat.GuardBroken");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_CATALYST_FULL, "Event.Catalyst.Full");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_CATALYST_SURGE, "Event.Catalyst.Surge");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_CATALYST_BURST, "Event.Catalyst.Burst");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_STAMINA_EMPTY, "Event.Stamina.Empty");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_EQUIP_SWORD, "Event.Equip.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_EQUIP_GUN, "Event.Equip.Gun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_UNEQUIP_SWORD, "Event.Unequip.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_EVENT_UNEQUIP_GUN, "Event.Unequip.Gun");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ABILITY, "Cooldown.Ability");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ABILITY_JUMP, "Cooldown.Ability.Jump");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM, "Cooldown.Item");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_COMMON, "Cooldown.Item.Common");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_FIRSTAID, "Cooldown.Item.FirstAid");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_STAMINA, "Cooldown.Item.Stamina");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_VIOLICALL, "Cooldown.Item.ViolicAll");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_COOLDOWN_ITEM_COREBATTERY, "Cooldown.Item.CoreBattery");