#include "KRGameplayCueTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_ITEM_LIGHT, "GameplayCue.Item.Light");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_START, "GameplayCue.StarDash.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_DASH, "GameplayCue.StarDash.Dash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_SLASH, "GameplayCue.StarDash.Slash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_FINISH, "GameplayCue.StarDash.Finish");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_STARCOMPLETE, "GameplayCue.StarDash.StarComplete");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_LAUNCH, "GameplayCue.AerialCombo.Launch");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_DASH, "GameplayCue.AerialCombo.Dash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_HIT, "GameplayCue.AerialCombo.Hit");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_FINISH, "GameplayCue.AerialCombo.Finish");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_GUARD_IMPACT, "GameplayCue.Guard.Impact");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_GUARD_DEFELCT, "GameplayCue.Guard.Deflect");