#include "KRGameplayCueTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_ITEM_LIGHT, "GameplayCue.Item.Light");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_START, "GameplayCue.StarDash.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_DASH, "GameplayCue.StarDash.Dash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_SLASH, "GameplayCue.StarDash.Slash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_FINISH, "GameplayCue.StarDash.Finish");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_STARDASH_STARCOMPLETE, "GameplayCue.StarDash.StarComplete");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_COREDRIVE_SURGE_LOOP, "GameplayCue.CoreDrive.Surge.Loop");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_COREDRIVE_BURST_LOOP, "GameplayCue.CoreDrive.Burst.Loop");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_COREDRIVE_BURST_HIT, "GameplayCue.CoreDrive.Burst.Hit");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_LAUNCH, "GameplayCue.AerialCombo.Launch");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_DASH, "GameplayCue.AerialCombo.Dash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_HIT, "GameplayCue.AerialCombo.Hit");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_AERIALCOMBO_FINISH, "GameplayCue.AerialCombo.Finish");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_GUARD_IMPACT, "GameplayCue.Guard.Impact");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_GUARD_DEFELCT, "GameplayCue.Guard.Deflect");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_INTERACTION_SCAN_SENSE_START, "GameplayCue.Interaction.Scan.Sense.Start");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_INTERACTION_SCAN_SENSE_ENEMY, "GameplayCue.Interaction.Scan.Sense.Enemy");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_INTERACTION_PICKUP, "GameplayCue.Interaction.PickUp");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_INTERACTION_LADDER_CLIMB, "GameplayCue.Interaction.Ladder.Climb");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_INTERACTION_BOX_OPEN, "GameplayCue.Interaction.Box.Open");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_GAMEPLAYCUE_INTERACTION_SAVE_FIRE, "GameplayCue.Interaction.Save.Fire");
