#include "KRItemTypeTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD, "ItemType.Equip.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN, "ItemType.Equip.Gun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE, "ItemType.Equip.GunModule");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORDMODULE, "ItemType.Equip.SwordModule");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD, "ItemType.Equip.Head");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME, "ItemType.Equip.Costume");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME, "ItemType.Consume");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_FIRSTAID, "ItemType.Consume.Potion.FirstAid");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_STAMINA, "ItemType.Consume.Potion.Stamina");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_VIOLICALL, "ItemType.Consume.Potion.ViolicAll");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_ATKBOOST, "ItemType.Consume.Potion.AtkBoost");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_SUPPRESS, "ItemType.Consume.Potion.Suppress");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_COREBATTERY, "ItemType.Consume.Potion.CoreBattery");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_INSURANCE_COIN, "ItemType.Consume.Insurance.Coin");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_INSURANCE_WALLET, "ItemType.Consume.Insurance.Wallet");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_KEY, "ItemType.Consume.Key");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_TOOL_LIGHT, "ItemType.Consume.Tool.Light");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL, "ItemType.Material");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL_SCRAP, "ItemType.Material.Scrap");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL_TECH, "ItemType.Material.Tech");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL_DOC, "ItemType.Material.Doc");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_QUEST, "ItemType.Quest");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORDMODULE_FATALDA, "ItemType.Equip.SwordModule.FatalDA");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORDMODULE_PULSEBM, "ItemType.Equip.SwordModule.PulseBM");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORDMODULE_DUALPS, "ItemType.Equip.SwordModule.DualPS");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORDMODULE_LIGHTSM, "ItemType.Equip.SwordModule.LightSM");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE_IONIC, "ItemType.Equip.GunModule.IonIC");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE_KINETICFA, "ItemType.Equip.GunModule.KineticFA");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE_OVERLOADCM, "ItemType.Equip.GunModule.OverloadCM");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE_ZEROKM, "ItemType.Equip.GunModule.ZeroKM");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE_COMPRESSEDBB, "ItemType.Equip.GunModule.CompressedBB");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE_RAPIDTG, "ItemType.Equip.GunModule.RapidTG");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_BLACKSTEELEX, "ItemType.Equip.Sword.BlackSteelEx");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_REDPULSEBL, "ItemType.Equip.Sword.RedPulseBl");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_AFTERGLOWJU, "ItemType.Equip.Sword.AfterGlowJu");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_ABYSSALED, "ItemType.Equip.Sword.AbyssalEd");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_AMARANTHRH, "ItemType.Equip.Sword.AmaranthRh");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_HEARTOFWR, "ItemType.Equip.Sword.HeartofWR");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_TEALLB, "ItemType.Equip.Sword.TealLB");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD_VIOLETOA, "ItemType.Equip.Sword.VioletOa");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN_IGCM45RED, "ItemType.Equip.Gun.IGCM45Red");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN_IGCM45GREEN, "ItemType.Equip.Gun.IGCM45Green");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN_IGCM45BLUE, "ItemType.Equip.Gun.IGCM45Blue");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN_IGCM45BLACK, "ItemType.Equip.Gun.IGCM45Black");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN_IGCM45WHITE, "ItemType.Equip.Gun.IGCM45White");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD_COREBUNNYRED, "ItemType.Equip.Head.CoreBunnyRed");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD_COREBUNNYGREEN, "ItemType.Equip.Head.CoreBunnyGreen");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD_COREBUNNYBLUE, "ItemType.Equip.Head.CoreBunnyBlue");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD_COREBUNNYBLACK, "ItemType.Equip.Head.CoreBunnyBlack");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD_COREBUNNYWHITE, "ItemType.Equip.Head.CoreBunnyWhite");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME_REQUIEMRED, "ItemType.Equip.Costume.RequiemRed");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME_REQUIEMGREEN, "ItemType.Equip.Costume.RequiemGreen");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME_REQUIEMBLUE, "ItemType.Equip.Costume.RequiemBlue");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME_REQUIEMBLACK, "ItemType.Equip.Costume.RequiemBlack");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME_REQUIEMWHITE, "ItemType.Equip.Costume.RequiemWhite");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_ATK, "Weapon.Stat.Atk");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_CRITCHANCE, "Weapon.Stat.CritChance");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_CRITMULTI, "Weapon.Stat.CritMulti");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_RANGE, "Weapon.Stat.Range");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_CAPACITY, "Weapon.Stat.Capacity");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_RELOADTIME, "Weapon.Stat.ReloadTime");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_STAT_ATTACKSPEED, "Weapon.Stat.AttackSpeed");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_MODULE, "Fragment.Item.Module");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_CONSUMABLE, "Fragment.Item.Consumable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_MATERIAL, "Fragment.Item.Material");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_QUEST, "Fragment.Item.Quest");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_COSTUME, "Fragment.Item.Costume");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_ENHANCEABLE, "Fragment.Item.Enhanceable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_EQUIPPABLE, "Fragment.Item.Equippable");
	
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_COMMON, "Rarity.Common");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_UNCOMMON, "Rarity.Uncommon");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_RARE, "Rarity.Rare");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_EPIC, "Rarity.Epic");