#include "KRItemTypeTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORD, "ItemType.Equip.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUN, "ItemType.Equip.Gun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_GUNMODULE, "ItemType.Equip.GunModule");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_SWORDMODULE, "ItemType.Equip.SwordModule");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_HEAD, "ItemType.Equip.Head");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_EQUIP_COSTUME, "ItemType.Equip.Costume");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME, "ItemType.Consume");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_FIRSTAID, "ItemType.Consume.Potion.FirstAid");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_STAMINA, "ItemType.Consume.Potion.Stamina");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_VIOLICALL, "ItemType.Consume.Potion.ViolicAll");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_ATKBOOST, "ItemType.Consume.Potion.AtkBoost");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_SUPPRESS, "ItemType.Consume.Potion.Suppress");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_POTION_COREBATTERY, "ItemType.Consume.Potion.CoreBattery");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_INSURANCE_COIN, "ItemType.Consume.Insurance.Coin");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_INSURANCE_WALLET, "ItemType.Consume.Insurance.Wallet");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_KEY, "ItemType.Consume.Key");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_CONSUME_TOOL_LIGHT, "ItemType.Consume.Tool.Light");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL_SCRAP, "ItemType.Material.Scrap");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL_TECH, "ItemType.Material.Tech");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_MATERIAL_DOC, "ItemType.Material.Doc");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_ITEMTYPE_QUEST, "ItemType.Quest");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_SWORD_FATALDRIVEAMP, "Weapon.Sword.FatalDriveAmp");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_SWORD_PULSEBLADEMOTOR, "Weapon.Sword.PulseBladeMotor");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_SWORD_DUALPHASESURGE, "Weapon.Sword.DualPhaseSurge");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_SWORD_LIGHTSYNCMATRIX, "Weapon.Sword.LightSyncMatrix");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_GUN_IONIMPACTCHAMBER, "Weapon.Gun.IonImpactChamber");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_GUN_COUNTERRECOILDAMP, "Weapon.Gun.CounterRecoilDamp");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_GUN_OVERLOADCOMPMAGAZINE, "Weapon.Gun.OverloadCompMagazine");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_GUN_ZEROKICKMOUNT, "Weapon.Gun.ZeroKickMount");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_GUN_MICROPRECISIONBARREL, "Weapon.Gun.MicroPrecisionBarrel");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_WEAPON_GUN_RAPIDTIMINGGEAR, "Weapon.Gun.RapidTimingGear");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_MODULE, "Fragment.Item.Module");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_CONSUMABLE, "Fragment.Item.Consumable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_MATERIAL, "Fragment.Item.Material");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_QUEST, "Fragment.Item.Quest");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_FRAGMENT_ITEM_COSTUME, "Fragment.Item.Costume");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_COMMON, "Rarity.Common");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_UNCOMMON, "Rarity.Uncommon");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_RARE, "Rarity.Rare");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_RARITY_EPIC, "Rarity.Epic");
