#include "KRNPCTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_NPC_TYPE_MERCHANT, "NPC.Type.Merchant");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_NPC_TYPE_BLACKSMITH, "NPC.Type.BlackSmith");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_NPC_TYPE_CIVILIAN, "NPC.Type.Civilian");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_NPC_TYPE_CLARA, "NPC.Type.Clara");
