#include "KRPlayerTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_SLASH, "Player.Action.Slash");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_FIRE, "Player.Action.Fire");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_CHARGEATTACK, "Player.Action.ChargeAttack");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_COREDRIVESURGE, "Player.Action.CoreDriveSurge");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_COREDRIVEBURST, "Player.Action.CoreDriveBurst");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_ADDITEM, "Player.Action.AddItem");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_ACTION_REMOVEITEM, "Player.Action.RemoveItem");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_SKILL, "Player.Skill");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_MODE_BASE, "Player.Mode.Base");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_MODE_SWORD, "Player.Mode.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_MODE_GUN, "Player.Mode.Gun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_MODE_UI, "Player.Mode.UI");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_MODE_LADDER, "Player.Mode.Ladder");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_WEAPON_SWORD, "Player.Weapon.Sword");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_PLAYER_WEAPON_GUN, "Player.Weapon.Gun");
