#include "KRSetByCallerTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_BASEDAMAGE, "SetByCaller.BaseDamage");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_ATTACKTYPE_LIGHT, "SetByCaller.AttackType.Light");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_ATTACKTYPE_CHARGE, "SetByCaller.AttackType.Charge");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_CONSUME_POWER, "SetByCaller.Consume.Power");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_CONSUME_DURATION, "SetByCaller.Consume.Duration");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_CONSUME_COOLDOWN, "SetByCaller.Consume.Cooldown");