#include "KRSetByCallerTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_BASEDAMAGE, "SetByCaller.BaseDamage");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_ATTACKTYPE_LIGHT, "SetByCaller.AttackType.Light");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SETBYCALLER_ATTACKTYPE_CHARGE, "SetByCaller.AttackType.Charge");
