#include "KRShopTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_CURRENCY_PURCHASE_GEARING, "Currency.Purchase.Gearing");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_CURRENCY_SKILL_CORBYTE, "Currency.Skill.Corbyte");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_CURRENCY_MATERIAL, "Currency.Material");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_CURRENCY_EVENT, "Currency.Event");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_VENDOR_OFFICIAL, "Shop.Vendor.Official");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_VENDOR_BLACK, "Shop.Vendor.Black");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_VENDOR_SORABELL, "Shop.Vendor.Sorabell");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_STABILITY_NORMAL, "Shop.Stability.Normal");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_STABILITY_CAUTION, "Shop.Stability.Caution");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_STABILITY_EMERGENCY, "Shop.Stability.Emergency");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_DISCOUNT, "Shop.Discount");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_SERVICE_ENHANCE, "Shop.Service.Enhance");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SHOP_SERVICE_REPAIR, "Shop.Service.Repair");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_POOL_ALWAYSON, "Pool.AlwaysOn");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_POOL_ROTATION_R1, "Pool.Rotation.R1");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_POOL_ROTATION_R2, "Pool.Rotation.R2");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_POOL_ROTATION_R3, "Pool.Rotation.R3");
