#include "KRSkillTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_SKILL_ATTACK, "Skill.Attack");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SKILL_SURVIVAL, "Skill.Survival");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_SKILL_UTILITY, "Skill.Utility");
