#pragma once

#include "NativeGameplayTags.h"

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SKILL_ATTACK);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SKILL_SURVIVAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SKILL_UTILITY);
