

#pragma once

#include "NativeGameplayTags.h"

// ============================================================
// SOUND TAGS - Movement
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_STONE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_GRASS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_SAND);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_METAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_WALK_WOOD);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_STONE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_GRASS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_SAND);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_METAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_FOOTSTEP_RUN_WOOD);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_NORMAL_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_NORMAL_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_NORMAL_WOOD);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_NORMAL_CONCRETE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_HEAVY_DEFAULT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_HEAVY_DIRT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_HEAVY_WOOD);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOVEMENT_LANDING_HEAVY_CONCRETE);

// ============================================================
// SOUND TAGS - Mobility
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOBILITY_DODGE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOBILITY_ROLL_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOBILITY_ROLL_END);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOBILITY_JUMP_VOICE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_MOBILITY_JUMP_UP);

// ============================================================
// SOUND TAGS - Stealth
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_STEALTH_ENTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_STEALTH_EXIT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_STEALTH_KILL);

// ============================================================
// SOUND TAGS - Combat Sword
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_EQUIP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_HOLSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_COMBO1);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_COMBO2);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_COMBO3);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_WHOOSH);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_CHARGE_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_CHARGE_LOOP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_CHARGE_RELEASE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_CHARGE_QUICKATTACK);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_VOICE01);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_VOICE02);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_VOICE03);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_SWORD_ATTACK_VOICE04);

// ============================================================
// SOUND TAGS - Combat Gun
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_EQUIP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_HOLSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_FIRE_NORMAL);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_FIRE_AUTO);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_RELOAD_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_RELOAD_LOOP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_RELOAD_END);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_DRYFIRE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_COMBAT_GUN_RICOCHET);

// ============================================================
// SOUND TAGS - Defense
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DEFENSE_GUARD_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DEFENSE_GUARD_LOOP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DEFENSE_GUARD_IMPACT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DEFENSE_GUARD_DEFLECT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DEFENSE_PARRY_ATTEMPT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DEFENSE_PARRY_SUCCESS);

// ============================================================
// SOUND TAGS - Damage & Impact
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_PLAYER_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_PLAYER_MEDIUM);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_PLAYER_HEAVY);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_PLAYER_DEATH);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_HUMAN_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_HUMAN_MEDIUM);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_HUMAN_HEAVY);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_MONSTER_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_MONSTER_MEDIUM);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_MONSTER_HEAVY);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_SEMIBOSS_LIGHT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_SEMIBOSS_MEDIUM);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_DAMAGE_HIT_ENEMY_SEMIBOSS_HEAVY);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_SWORD_ENEMY_HUMAN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_SWORD_ENEMY_MONSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_SWORD_ENEMY_SEMIBOSS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_SWORD_ENVIRONMENT);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_GUN_ENEMY_HUMAN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_GUN_ENEMY_MONSTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_GUN_ENEMY_SEMIBOSS);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_IMPACT_GUN_ENVIRONMENT);

// ============================================================
// SOUND TAGS - UI & Resources
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_UI_WEAPONSLOT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_UI_STAMINA_CONSUME);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_UI_STAMINA_DEPLETED);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_UI_COREDRIVE_CHARGE1);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_UI_COREDRIVE_CHARGEFULL);

// ============================================================
// SOUND TAGS - Interaction
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_PICKUP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_CHEST_OPEN);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_CHEST_COMPLETE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_LADDER_ENTER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_LADDER_CLIMB);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_LADDER_DESCEND);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_INTERACTION_LADDER_EXIT);

// ============================================================
// SOUND TAGS - Boss
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_INTRO);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_AURA_LOOP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_PHASETRANSITION);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_ATTACKTELEGRAPH);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_AREAATTACK);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_ROAR);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_BOSS_DEATH);

// ============================================================
// SOUND TAGS - Special Skills (StarDash, AerialCombo, etc.)
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_STARDASH_START);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_STARDASH_DASH);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_STARDASH_DASH_LOOP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_STARDASH_SLASH);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_STARDASH_FINISH);

KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_AERIALCOMBO_LAUNCH);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_AERIALCOMBO_RISING);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_AERIALCOMBO_SLAM);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_AERIALCOMBO_HIT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_SKILL_AERIALCOMBO_FINISH);

// ============================================================
// SOUND TAGS - Category (for filtering/volume control)
// ============================================================
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_FOLEY);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_MAINWEAPON);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_IMPACT);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_UI);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_VOICE);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_AMBIENTLOOP);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_PLAYER);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_ENEMY);
KORAPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KRTAG_SOUND_CATEGORY_SKILL);
