#include "KRStateTag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_ATTACKING, "State.Acting.Attacking");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_GUARD, "State.Acting.Guard");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_EVADING, "State.Acting.Evading");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_SPRINTING, "State.Acting.Sprinting");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_JUMPING, "State.Acting.Jumping");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_INTERACTING, "State.Acting.Interacting");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_GRAPPLING, "State.Acting.Grappling");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_SCANNING, "State.Acting.Scanning");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_OVERDRIVING, "State.Acting.OverDriving");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_STEPPING, "State.Acting.Stepping");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_LADDERUP, "State.Acting.LadderUp");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_LADDERDOWN, "State.Acting.LadderDown");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_ACTING_LOCKON, "State.Acting.LockOn");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_HASCC_STUN, "State.HasCC.Stun");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_HASCC_SLOW, "State.HasCC.Slow");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_HASCC_COMA, "State.HasCC.Coma");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_RESTRICT_STAMINAREGEN, "State.Restrict.StaminaRegen");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_RESTRICT_WEAPONSWITCH, "State.Restrict.WeaponSwitch");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_RESTRICT_CATALYST, "State.Restrict.Catalyst");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_RESTRICT_INTERACT, "State.Restrict.Interact");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_RESTRICT_INPUT, "State.Restrict.Input");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_CATALYST_FULL, "State.Catalyst.Full");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_CATALYST_BURST, "State.Catalyst.Burst");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_INIT_SPAWNED, "State.Init.Spawned");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_INIT_DATAAVAILABLE, "State.Init.DataAvailable");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_INIT_DATAINITIALIZED, "State.Init.DataInitialized");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATE_INIT_GAMEPLAYREADY, "State.Init.GameplayReady");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATUS_ITEM_INUSE_ATKBOOST, "Status.Item.InUse.ATKBoost");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATUS_ITEM_INUSE_SUPPRESS, "Status.Item.InUse.Suppress");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_STATUS_ITEM_INUSE_LIGHT,    "Status.Item.InUse.Light");