#include "KRUITag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_PROGRESSBAR, "UI.Message.ProgressBar");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_GREYHP, "UI.Message.Progress.GreyHP");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_ITEMLOG, "UI.Message.ItemLog");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_WEAPON, "UI.Message.Weapon");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_QUICKSLOT, "UI.Message.QuickSlot");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_QUEST, "UI.Message.Quest");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_CURRENCY, "UI.Message.Currency");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_CONFIRM, "UI.Message.Confirm");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_TUTORIAL, "UI.Message.Tutorial");