#include "KRUITag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_PROGRESSBAR, "UI.Message.ProgressBar");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_CURRENCY, "UI.Message.Currency");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_ITEMLOG, "UI.Message.ItemLog");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_QUEST, "UI.Message.Quest");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_WEAPONSWITCH, "UI.Message.WeaponSwitch");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_QUICKSLOT, "UI.Message.QuickSlot");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_PROGRESSBAR_HP, "UI.ProgressBar.HP");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_PROGRESSBAR_GREYHP, "UI.ProgressBar.GreyHP");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_PROGRESSBAR_STAMINA, "UI.ProgressBar.Stamina");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_PROGRESSBAR_COREDRIVE, "UI.ProgressBar.CoreDrive");
