#include "KRUITag.h"

UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_GUARD, "UI.Message.Guard");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_ITEMLOG, "UI.Message.ItemLog");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_WEAPON, "UI.Message.Weapon");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_QUICKSLOT, "UI.Message.QuickSlot");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_EQUIPSLOT, "UI.Message.EquipSlot");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_QUEST, "UI.Message.Quest");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_CURRENCY, "UI.Message.Currency");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_SHOPSTOCKUPDATED, "UI.Message.ShopStockUpdated");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_CONFIRM, "UI.Message.Confirm");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_TUTORIAL, "UI.Message.Tutorial");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_MESSAGE_EQUIPMENTUI, "UI.Message.EquipmentUI");

UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_QUICKSLOT_NORTH, "UI.QuickSlot.North");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_QUICKSLOT_EAST, "UI.QuickSlot.East");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_QUICKSLOT_SOUTH, "UI.QuickSlot.South");
UE_DEFINE_GAMEPLAY_TAG(KRTAG_UI_QUICKSLOT_WEST, "UI.QuickSlot.West");